### ISSUE TITLE
加英文詞彙

### ISSUE THREAD

**Issue by nereuseng** [PJCHENder/cn2tw4programmer#1]
請問能支援繁體中文旁邊加上英文原文的功能嗎？
像是：陣列(Array)
之後看原文也不會那麼吃力
謝謝！

**Comment by PJCHENder** [comment]
我覺得是蠻不錯的建議，我先自己加上去測試看看，沒有問題的話再把功能添加進去，謝謝：）

**Comment by PJCHENder** [comment]
@nereuseng 在這次的更新中，所有轉換過的詞彙會用「底線」標註，然後滑鼠移到該詞彙上方一段時間後會出現英文原文，可以在測試看看，謝謝！

0f522840ed8fc65caac9a2d3ae862a20511c9e3b
